name: NightlyBuild

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - test

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ks-installer
  IMAGE_REPO: kubespheredev
  IMAGE_VERSION: latest

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
        tag=nightly-$(date '+%Y%m%d')
        sed -i "/ks_image_tag/s/\:.*/\: $tag/g" roles/download/defaults/main.yml 
        docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$IMAGE_REPO/$IMAGE_NAME

          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION
          
          tag=nightly-$(date '+%Y%m%d')

          docker tag $IMAGE_NAME $IMAGE_ID:${tag}
          docker push $IMAGE_ID:${tag}

      - name: slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        if: always()
